@extends('admin.layouts.app')
@section('content')
@php($isEdit=(bool)$opportunity)
<div class="px-4 sm:px-0"><div class="mb-6 flex items-center justify-between"><div><h1 class="text-2xl font-bold text-gray-900">{{ $isEdit?'编辑商机':'新增商机' }}</h1><p class="mt-1 text-sm text-gray-500">记录成交阶段、金额与明确的下一步。</p></div><a href="{{ route('admin.crm.opportunities.index') }}" class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700">返回管道</a></div>@include('admin.crm.partials.nav',['currentCrmTab'=>'opportunities'])
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><form method="POST" action="{{ $isEdit?route('admin.crm.opportunities.update',['opportunityId'=>$opportunity->id]):route('admin.crm.opportunities.store') }}" class="space-y-6">@csrf @if($isEdit)@method('PUT')@endif
<section class="rounded-lg border border-gray-200 bg-white p-6 shadow-sm"><div class="grid gap-5 md:grid-cols-2">
<label class="md:col-span-2"><span class="mb-1.5 block text-sm font-medium text-gray-700">商机名称 *</span><input name="name" required value="{{ old('name',$opportunity?->name ?: $inquiry?->subject) }}" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">客户 *</span><select name="customer_id" required class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500">@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((int)old('customer_id',$selectedCustomerId)===$customer->id)>{{ $customer->company_name ?: $customer->contact_person }}</option>@endforeach</select></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">业务容器</span><select name="collection_id" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"><option value="">未指定</option>@foreach($collectionOptions as $option)<option value="{{ $option['id'] }}" @selected((int)old('collection_id',$opportunity?->collection_id ?: $inquiry?->collection_id)===$option['id'])>{{ $option['name'] }}</option>@endforeach</select></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">主要联系人</span><select name="primary_contact_id" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"><option value="">未指定</option>@foreach($customers as $customer)@foreach($customer->contacts as $contact)<option value="{{ $contact->id }}" @selected((int)old('primary_contact_id',$opportunity?->primary_contact_id)===$contact->id)>{{ $customer->company_name }} · {{ $contact->name }}{{ $contact->title ? ' · '.$contact->title : '' }}</option>@endforeach @endforeach</select></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">阶段</span><select name="stage" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500">@foreach($stages as $key=>$label)<option value="{{ $key }}" @selected(old('stage',$opportunity?->stage ?: 'qualified')===$key)>{{ $label }}</option>@endforeach</select></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">负责人</span><select name="owner_admin_id" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"><option value="">未指定</option>@foreach($employeeOptions as $id=>$label)<option value="{{ $id }}" @selected((int)old('owner_admin_id',$opportunity?->owner_admin_id)===$id)>{{ $label }}</option>@endforeach</select></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">金额</span><div class="flex"><select name="currency" class="w-24 rounded-l-md border border-r-0 border-gray-300 px-2 py-2 text-sm"><option>USD</option><option>EUR</option><option>CNY</option></select><input type="number" step="0.01" min="0" name="amount" value="{{ old('amount',$opportunity?->amount ?: 0) }}" class="min-w-0 flex-1 rounded-r-md border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"></div></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">成交概率 %</span><input type="number" min="0" max="100" name="probability" value="{{ old('probability',$opportunity?->probability ?: 20) }}" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm"></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">预计成交日期</span><input type="date" name="expected_close_date" value="{{ old('expected_close_date',$opportunity?->expected_close_date?->format('Y-m-d')) }}" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm"></label>
<label><span class="mb-1.5 block text-sm font-medium text-gray-700">下一步时间</span><input type="datetime-local" name="next_step_at" value="{{ old('next_step_at',$opportunity?->next_step_at?->format('Y-m-d\TH:i')) }}" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm"></label>
<label class="md:col-span-2"><span class="mb-1.5 block text-sm font-medium text-gray-700">下一步动作</span><input name="next_step" value="{{ old('next_step',$opportunity?->next_step) }}" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm"></label>
<label class="md:col-span-2"><span class="mb-1.5 block text-sm font-medium text-gray-700">输单原因（阶段为输单时必填）</span><textarea name="lost_reason" rows="3" class="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm">{{ old('lost_reason',$opportunity?->lost_reason) }}</textarea></label>
</div><input type="hidden" name="source_inquiry_id" value="{{ old('source_inquiry_id',$opportunity?->source_inquiry_id ?: $inquiry?->id) }}"><div class="mt-6 flex justify-end"><button class="rounded-md bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">保存商机</button></div></section></form>
<aside class="space-y-6">@if($isEdit)<section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">新建待办</h2><div class="mt-4">@include('admin.crm.partials.task-form',['customer_id'=>$opportunity->customer_id,'opportunity_id'=>$opportunity->id])</div></section><section class="rounded-lg border border-gray-200 bg-white shadow-sm"><div class="border-b border-gray-100 px-5 py-4"><h2 class="font-semibold text-gray-900">商机待办</h2></div><div class="divide-y divide-gray-100">@forelse($opportunity->tasks as $task)@include('admin.crm.partials.task-row',['task'=>$task])@empty<div class="p-5 text-sm text-gray-500">暂无待办</div>@endforelse</div></section>@else<section class="rounded-lg border border-blue-100 bg-blue-50 p-5 text-sm leading-6 text-blue-800">建议只把已确认存在真实采购可能的询盘转成商机，普通咨询继续留在询盘中即可。</section>@endif</aside></div></div>
@endsection
